
package tetris_03;

import javax.swing.JFrame;

public class TetrisFrameModificado extends javax.swing.JFrame {

    int dificuldade;
    String nome;
           
    /**
     * Creates new form TetrisFrameModificado
     */
    public TetrisFrameModificado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dificuldades = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        nomeJogador = new javax.swing.JTextField();
        RadioButtonFacil = new javax.swing.JRadioButton();
        RadioButtonMedio = new javax.swing.JRadioButton();
        RadioButtonDificil = new javax.swing.JRadioButton();
        jButton1Jogar = new javax.swing.JButton();
<<<<<<< HEAD
        jLabel2 = new javax.swing.JLabel();
=======
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris_03/tetris.png"))); // NOI18N

        jLabelNome.setText("GAMER");

        nomeJogador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nomeJogador.setText("Insira seu nome Gamer");
        nomeJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeJogadorActionPerformed(evt);
            }
        });

        dificuldades.add(RadioButtonFacil);
        RadioButtonFacil.setText("FÁCIL");
        RadioButtonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFacilActionPerformed(evt);
            }
        });

        dificuldades.add(RadioButtonMedio);
        RadioButtonMedio.setText("MÉDIO");
        RadioButtonMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMedioActionPerformed(evt);
            }
        });

        dificuldades.add(RadioButtonDificil);
        RadioButtonDificil.setText("DIFÍCIL");
        RadioButtonDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDificilActionPerformed(evt);
            }
        });

        jButton1Jogar.setText("JOGAR");
        jButton1Jogar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1Jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1JogarActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        jLabel2.setText("jLabel2");

=======
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
=======
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(jLabelNome)
                        .addGap(50, 50, 50)
                        .addComponent(nomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1Jogar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioButtonFacil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioButtonMedio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonDificil)))
=======
                        .addComponent(RadioButtonFacil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonDificil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(50, 50, 50)
                        .addComponent(nomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Jogar)
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
=======
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(nomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonFacil)
                    .addComponent(RadioButtonMedio)
                    .addComponent(RadioButtonDificil))
<<<<<<< HEAD
                .addGap(47, 47, 47)
                .addComponent(jButton1Jogar)
                .addContainerGap(61, Short.MAX_VALUE))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1Jogar)
                .addContainerGap(59, Short.MAX_VALUE))
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jButton1JogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1JogarActionPerformed
        // TODO add your handling code here:
        System.out.println(evt);
        this.nome = nomeJogador.getText();
        JFrame x = new JFrame();
        TetrisPanel tp= new TetrisPanel(x, this.dificuldade, this.nome);
        x.add(tp);
        x.setTitle("Tetris");
        x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        x.setResizable(true);
        x.pack();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1JogarActionPerformed
=======
    private void nomeJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJogadorActionPerformed
        // TODO add your handling code here:
        this.nome = evt.toString();
        
    }//GEN-LAST:event_nomeJogadorActionPerformed
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482

    private void RadioButtonDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDificilActionPerformed
        // TODO add your handling code here:
        this.dificuldade = 40;
    }//GEN-LAST:event_RadioButtonDificilActionPerformed

<<<<<<< HEAD
=======
    private void jButton1JogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1JogarActionPerformed
        // TODO add your handling code here:
        TetrisPanel tp= new TetrisPanel(this, this.dificuldade, this.nome);            
       
   
        this.setVisible(true);
        this.setLocationRelativeTo(null);  
    }//GEN-LAST:event_jButton1JogarActionPerformed

>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
    private void RadioButtonMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMedioActionPerformed
        // TODO add your handling code here:
        this.dificuldade = 20;
    }//GEN-LAST:event_RadioButtonMedioActionPerformed

    private void RadioButtonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFacilActionPerformed
        // TODO add your handling code here:
        this.dificuldade = 1;
    }//GEN-LAST:event_RadioButtonFacilActionPerformed

<<<<<<< HEAD
    private void nomeJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJogadorActionPerformed
        // TODO add your handling code here:
        this.nome = nomeJogador.getText();
        System.out.println(nome);

    }//GEN-LAST:event_nomeJogadorActionPerformed

=======
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TetrisFrameModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TetrisFrameModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TetrisFrameModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TetrisFrameModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TetrisFrameModificado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonDificil;
    private javax.swing.JRadioButton RadioButtonFacil;
    private javax.swing.JRadioButton RadioButtonMedio;
    private javax.swing.ButtonGroup dificuldades;
    private javax.swing.JButton jButton1Jogar;
    private javax.swing.JLabel jLabel1;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel2;
=======
>>>>>>> 45e3d2d187b90dcbcbcdfa8d2bb69145e9c3b482
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JTextField nomeJogador;
    // End of variables declaration//GEN-END:variables
}
